env: "local"
data_source_name: postgres://postgres:qwerty@db:5432/postgres
# db:
#    host: "db"
#    port: "5432"
#    username: "postgres"
#    dbname: "postgres"
#    sslmode: "disable"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 8s